---
- name: Configure Apache Web Server
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and Enable Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy Custom Index Page
      ansible.builtin.copy:
        src: /home/student/ansible/ivolve.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'
    - name: permanently enable https service, also enable it immediately if possible
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true